### ISSUE TITLE
Support for iOS?

### ISSUE THREAD

**Issue by andreragsilva** [google/nearby#10]
Will there ever be support for iOS?

**Comment by bourdakos1** [comment]
We currently have support for iOS through Swift Package Manager. This isn’t yet documented, but we will hopefully have some new documentation soon.

Until then, feel free to re-open this issue with any questions on how to get this running on iOS.

**Comment by andreragsilva** [comment]
@bourdakos1 thank you for the update 👀

**Comment by IgVelasco** [comment]
Hi, I'm looking to be able to install this in my iOS project, any links or documentation that could help me?

Thank you for the help

**Comment by bourdakos1** [comment]
Hey @IgVelasco, you can check out the sample app here: https://github.com/google/nearby/tree/main/connections/swift/NearbyConnections/Example

and the full getting started guide here: https://developers.google.com/nearby/connections/swift/get-started

Hope this helps :)

**Comment by IgVelasco** [comment]
Hey!

Yea saw all those links already, they were helpful. But I'm encountering issues when I try adding the package to my swift code.

For more context, I'm developing a Flutter plugin to use this library and make it easier to use and connect cross-device. So I need to add the package inside the Development Pod of my plugin.

But when I do the module is nowhere to be found, do you have any idea why that could be?

NearbyCoreAdapter was showing in the imports, but not NearbyConnections!

![image](https://github.com/google/nearby/assets/14189126/0a82eef5-9b2e-4ecc-9ff2-38f26643ce67)


I hope you can help me, if not thanks for the fast response!

**Comment by bourdakos1** [comment]
Do you mind sharing a screenshot of the “Package Dependencies” tab of your project settings?

**Comment by IgVelasco** [comment]
Sorry for the delay, I think the problem is that since Flutter uses CocoaPods it has issues getting the dependency inside the development pod. Is there any plan on getting it to work in CocoaPods? 

<img width="748" alt="image" src="https://github.com/google/nearby/assets/14189126/53e22fda-5c34-4efa-8970-d649f6c8c6eb">

**Comment by bourdakos1** [comment]
hmm yea I agree, I think that CocoaPods doesn't play nice with SPM. I was able to get NearbyConnections working with the Flutter Runner project directly, but had the same issue when trying to add NearbyConnections to a Flutter plugin. This person https://forums.swift.org/t/possible-to-use-spm-packages-from-cocoapods-pods-project/53187 had a similar experience where one of the sub-package are visible, but not the top level package.

It sounds like Flutter might be adding SPM support for plugins as discussed here: https://github.com/flutter/flutter/issues/33850 and https://github.com/flutter/flutter/issues/126005

Unfortunately, I don't have much CocoaPod experience. I don't think I'll be able to get CocoaPods working with the project anytime soon, as the project is quite large and has dependencies on other projects that also don't support CocoaPods.

I recommend giving the Flutter issues a thumbs-up, so they know there are people interested in using SPM in plugins and prioritize the feature.

In the meantime, if NearbyCoreAdapter is working, you could just use that since NearbyConnections is just a very thin wrapper on top of NearbyCoreAdapter.

I hope this helps a bit, sorry it's not ideal 😕

**Comment by IgVelasco** [comment]
Awesome response, yeah I got to the same point, thanks for helping me corroborate the issue I was having. I'm thinking of maybe making a React Native module. Thanks again for the help!

**Comment by eliabruni** [comment]
> Awesome response, yeah I got to the same point, thanks for helping me corroborate the issue I was having. I'm thinking of maybe making a React Native module. Thanks again for the help!

Hey, just to say that a react-native module would be awesome and would definitely get quite popular - there is quite a gap to fill.

**Comment by IgVelasco** [comment]
I was able to get it running with flutter adding it manually, and using NearbyCoreAdapter. Thanks for making the ticket for tracking it! @bourdakos1

**Comment by IgVelasco** [comment]
Hi, when trying to send data between Android and iOS im getting the following error in XCode:

```
<PATH>/SourcePackages/checkouts/nearby/third_party/protobuf/src/google/protobuf/message_lite.cc:134] Can't parse message of type "securemessage.SecureMessage" because it is missing required fields: (cannot determine missing fields for lite message)
[ERROR] VerifyDecryptPayload: error parsing SecureMessage.
[ERROR] DecodeMessageFromPeer: Failed to verify message.
```

Once in a while connects as expected, but this error with so little information doesn't help to debug it
