### ISSUE TITLE
Connectins background Advertisement on IOS

### ISSUE THREAD

**Issue by Romoli-Gabriele** [google/nearby#1631]
I want to use connections to advertise in the background with WIFI and BLE on IOS but other devices only find me when I'm in the foreground. The background task runs without errors, how can I fix it?

The background task stops and restarts advertising every 30 seconds

With the Messages API it works calling publish every 30 seconds

**Comment by bourdakos1** [comment]
Hey @Romoli-Gabriele, sorry for the late response!

I’m not certain, but I’m guessing the Network framework doesn’t work in the background and the messages API was falling back to BLE. Nearby Connections doesn’t have BLE support enabled yet, so there’s nothing for it to fallback to.

If you could provide some sample code, I could take a closer look to see what the issue is.

**Comment by NiccoloCase** [comment]
any updates?

**Comment by bourdakos1** [comment]
I don't think Apple supports Wi-Fi LAN usage in the background. However, a code sample from you or @Romoli-Gabriele would be helpful to verify this.
