### ISSUE TITLE
BLE don't work betweeb Android (startDiscovering) and iOS (startAdvertising

### ISSUE THREAD

**Issue by Droppix** [google/nearby#2465]
Hi,

I tried to integrate Nearby with Android (startDiscovering) and iOS (startAdvertising: 
I used this example []https://github.com/google/nearby/tree/b80426a043356fe4820c66c17b83cc9ec6aeb073/connections/swift/NearbyConnections/Example

1/ If the 2 devices are on the same local network, it works fine.

2/ If I disable WIFI or change the WiFI network on iOS, to force the use of Bluetooth, it doesn't work, no detection on the Android side.

However, if I reverse the logic between Android (startAdvertising) and iOS (startDiscovering), iOS detects the endpoint, it's work!

Any ideas, suggestions?

Thanks

**Comment by bourdakos1** [comment]
Hi @Droppix

Nearby Connections iOS does not support Bluetooth yet. You can turn on the experimental feature with the following flag, but you may run into bugs: https://github.com/google/nearby/blob/dbb6550c2faca2b5eb87db5b0c5829b3fcdaea8e/connections/swift/NearbyCoreAdapter/Sources/GNCFlags.mm#L31

Nearby Connections on Android will automatically enable Wi-Fi when you call `startAdvertising`, so that may be why discovery succeeds when Android is the advertiser.

I'm closing this as a duplicate, because we are tracking Bluetooth (BLE) support in https://github.com/google/nearby/issues/1619, but feel free to continue the conversation in that issue :)
